*CU Boulder GEOL 3600, Oct 2025*

# Other ways to run Python code; Introduction to the Pandas package

#### Today's notebook and data files:

Download these from canvas and upload to the explore hub:

**`12_data_analysis_pandas.ipynb`**

**`USGS09058000_discharge_NoHead_20112021.csv`**

#### Today's topics

1. Other ways to run Python code: interactive sessions and `.py` files
2. Introduction to the Pandas data-management package



## Review from last week

### Python's built-in functions for file I/O

- `open()` opens a file for reading or writing
- It returns a **file object**
- File objects have three widely used functions for reading:
  - `read()`: read a certain number of characters as a string, or the entire file as one giant string
  - `readline()`: read one line at a time as a string
  - `readlines()`: read multiple lines, as a list of strings (one per line)

However, for data files, there are more convenient alternatives.


### Reading file data into a numpy array: loadtxt and genfromtxt

If our goal is to read the contents of a text file into a numpy array, numpy provides functions that makes this a bit easier:

`loadtxt()` - simple and effective when you have all numbers plus some comments or header lines <br>
`genfromtxt()` - useful when there are strings embedded in the data portion of the file <br>


## Ways to run Python code

There are several different ways to run Python code, including:

1. In a Jupyter notebook (which is what we've done so far in this class)
2. In an interactive session
3. In a text file with the extension `.py`

In all cases, the Python interpreter reads and executes the code *one line at a time*.

### Interactive sessions

#### <span style="color:green;">Exercise</span>

1. In the JupyterHub environment, open the Launcher
2. Select **Console** => **GEOL 3600**

This is an **interactive Python session**. You can use this to run Python instructions one line at a time.

Try running the following lines one at a time:

```
denver_alt_ft = 5280.
denver_alt_m = denver_alt_ft * 0.3048
print("The Mile High City has an altitude of", denver_alt_ft, "ft, or", denver_alt_m, "meters.")
```



### Python files

The traditional method of running computer programs is to write code in a text file. The file name must have an *extension* that indicates that it contains code in a particular language. For example, a C source-code file might be called `myprogram.c`, and a Fortran source-code file `myprogram.f`. 

**Python source-code files always end in `.py`**

#### <span style="color:green;">Exercise</span>

1. In the JupyterHub environment, open the Launcher
2. Select **Other** => **Python file**
3. Save the file as `hello.py`
4. Enter the following code in the file:

```
print("Hello!")
sec_per_year = 365.25 * 24 * 60 * 60
print("There are", sec_per_year, "seconds in an average year.")
```
5. Go back to the Launcher
6. Select **Other** => **Terminal**
7. This opens a terminal window. In that window, enter: `python hello.py`

This tells the operating system to run the program `python`. The `python` program then reads and executes each line in the file `hello.py`, one line at a time.

# Data analysis using the `pandas` library

## Overview

We will be looking at data on river discharge of the Upper Colorado River. 
This data set is a good example of tabular data, with a combination of dates, names, data quality strings, and numbers. In Python, the Python Data Analysis Library (a.k.a. Pandas) is really useful for working with this kind of data set..

The data file above contains discharge data file downloaded for the USGS station at Kremmling, CO, for the Upper Colorado River. The file has already been pre-processed to remove extraneous header information and convert it to CSV format. To see the original data, visit [https://waterdata.usgs.gov/nwis/uv?site_no=09058000&legacy=1](https://waterdata.usgs.gov/nwis/uv?site_no=09058000&legacy=1).

Python Learning Objectives:
1. Load csv data from a file using the Pandas library.
2. Get info on the data in a dataframe, and access data in DataFrames.
3. Create plots of data in DataFrames.
4. Save figures to file.

In [2]:
# Import the modules we will use
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:


# Example from last week of loadtxt on glacial data
# Our file has 2 header lines that we need to skip; 
# we use the skiprows parameter.
# It is comma-separated; we use the delimiter parameter.
har = np.loadtxt(
    "hardangerjokulen2006-2007.csv", skiprows=2, delimiter=","
)
print(har)

[[ 1.850e+03  1.865e+03  9.000e-02  2.700e+00 -1.450e+00]
 [ 1.800e+03  1.850e+03  3.930e+00  3.450e+00 -1.500e+00]
 [ 1.750e+03  1.800e+03  4.030e+00  3.600e+00 -1.600e+00]
 [ 1.700e+03  1.750e+03  3.460e+00  3.500e+00 -1.750e+00]
 [ 1.650e+03  1.700e+03  1.940e+00  3.200e+00 -1.900e+00]
 [ 1.600e+03  1.650e+03  7.500e-01  2.700e+00 -2.100e+00]
 [ 1.550e+03  1.600e+03  5.900e-01  2.350e+00 -2.300e+00]
 [ 1.500e+03  1.550e+03  5.700e-01  1.950e+00 -2.500e+00]
 [ 1.450e+03  1.500e+03  2.900e-01  1.730e+00 -2.700e+00]
 [ 1.400e+03  1.450e+03  1.900e-01  1.560e+00 -2.950e+00]
 [ 1.350e+03  1.400e+03  1.000e-01  1.390e+00 -3.200e+00]
 [ 1.300e+03  1.350e+03  1.000e-01  1.220e+00 -3.450e+00]
 [ 1.250e+03  1.300e+03  2.700e-01  1.050e+00 -3.700e+00]
 [ 1.200e+03  1.250e+03  3.600e-01  8.000e-01 -3.950e+00]
 [ 1.150e+03  1.200e+03  2.800e-01  5.500e-01 -4.250e+00]
 [ 1.100e+03  1.150e+03  1.100e-01  3.000e-01 -4.550e+00]
 [ 1.020e+03  1.100e+03  5.000e-02 -5.000e-02 -4.900e+00]]


## Introduction to `pandas`

### What is the Pandas Module?

The Python module **Pandas** is designed to efficiently work with tabular data.

Pandas provides a data structure called a `DataFrame`: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

The usual way to import it is:

```
import pandas as pd
```

In [ ]:
import pandas as pd

### Example: load a csv file into a pandas dataframe

In [ ]:
# read the data file posted with this excercise into a pandas dataframe

data = pd.read_csv('USGS09058000_discharge_NoHead_20112021.csv')

# print the first five lines to see whether it populated the fields
# with the head() method, you can see the structure of the data without having to print the entire dataframe.

print(data)


We have just created a Data Frame.<br>

A DataFrame is a 2-dimensional data structure that can store data of different types (including characters, integers, floating point values, factors and more) in columns. It is similar to a spreadsheet, or an database/ SQL table.

To get quick insight in what is in a dataframe, you can use the head() method or the tail() method.

You can check the type of the object data using the type module. The type() method or the  __class__ attribute tell us what type of object the variable points to.

Then: each column in a DataFrame also has its own type. We can use data.dtypes to view the data type for each column. int64 are numeric integer values, object are strings (letters and numbers), and float64 are numbers with decimals.

In [ ]:
# to get insight in the content of a dataframe, you can use the head() method or the tail() method:
data.head()
#data.tail()

In [ ]:
# the type() function works too
print(type(data))
print(data.__class__)

In [ ]:
data.dtypes

In [ ]:
# To rename the columns, create a list with new column names as strings
new_column_names = ['Agency', 'SiteNo', 'DateTime', 'Discharge_cfs']

# assign the new column names to the dataframe
data.columns = new_column_names

The values in each column of a Pandas DataFrame can be accessed using the specific column name. <br>
If we want to access more than one column at once, we use a list of column names. 

In [ ]:
# for example, if we just want to select the discharge in cu ft/sec
data[['Discharge_cfs']].head()

# or as a second example, we just want to select time and discharge
data[['DateTime', 'Discharge_cfs']].head()

### Manipulating data in a dataframe

In [ ]:
# Calculations
# We can also call the data using column names and manipulate the values in the column
# For example, here we convert the discharge from cubic feet per second to metric units m3/sec 
data['Discharge_m3sec'] = data['Discharge_cfs'] * 0.028316847 
data.head()

# So we added a column with the newly calculated parameter.

When Pandas imported the data, it read the station name (a number) as an integer and removed the initial zero. We can fix the station name by replacing the values of that column with a string.
Remember that the goal is to automate the process for multiple stations. Instead of writing the corrected station name ourselves, let’s build it from the values available in the DataFrame.

The Pandas method `unique()` returns a numpy array of the unique elements in the DataFrame. We want the first (and only) entry in that array, which has the index 0. We can build a string with the correct station name by casting that value as a string and concatenating it with an initial zero.

We can replace all values in the ‘Station’ column with this string through assignment and check the object type of each column to make sure it is no longer an integer.

In [ ]:
# manipulation of strings in one of the columns of the dataframe

new_station_name = "0" + str(data['SiteNo'].unique()[0])
data['SiteNo'] = new_station_name

data.head()

In [ ]:
# max, min and basic stats can be easily found with a couple of math methods built into pandas
print(data['Discharge_m3sec'].max())
print(data['Discharge_m3sec'].min())
print(data['Discharge_m3sec'].mean())
print(data['Discharge_m3sec'].std())

# also very handy for inquiries is to find the index of these max values
peakflowindex = data['Discharge_m3sec'].idxmax()
print(peakflowindex)

peakflowday = data['DateTime'][peakflowindex]
print(peakflowday)

## Handling Date and Time stamps

Different programming languages and software packages handle date and time stamps in their own unique ways. Pandas has a set of functions for creating and managing timeseries.

We need to convert the USGS entries in the DateTime column into a format that Pandas can work with. Luckily, the to_datetime function in the Pandas library can convert it directly. Note that this conversion takes up a bit of time, wait till you see those first five lines reported....


In [ ]:
# using the pd.to_datetime functionality
data['NewDateTime'] = pd.to_datetime(data['DateTime'])
data.head()

In [ ]:
#The entries in our DataFrame data are indexed by the number in bold on the left side of each row. 
# We can display a slice of the data using index ranges:

data[0:5]

## Creating data subsets and removing columns

We can select specific ranges of our data in both the row and column directions using either label or integer-based indexing.

loc: indexing via labels or integers <br>
iloc: indexing via integers <br>

To select a subset of rows AND columns from our DataFrame, we can use the loc method and the integer indices for both rows and columns. 

In [ ]:
data.loc[0:2, ['DateTime', 'Discharge_m3sec']]

In [ ]:
data.iloc[0:2, -2:]

In [ ]:
print('With iloc:', data.iloc[0:2, -2:].shape)
print('With loc:', data.loc[0:2, ['DateTime', 'Discharge_m3sec']].shape)

Since we can call individual columns (or lists of columns) from a DataFrame, the simplest way to remove columns is by creating a new DataFrame with only the columns we want.

In [ ]:
discharge_data = data[['DateTime', 'Discharge_m3sec']]
discharge_data

## Creating Plots of Pandas Dataframes

Pandas is well integrated with the matplotlib library that we used earlier in the tutorials. 
We can either use the same functions we used before with to plot data in NumPy arrays or we can use the plotting functions built into Pandas.

In [ ]:
import matplotlib.pyplot as plt

plt.plot(data['DateTime'], data['Discharge_cfs'])
plt.title('Gauging Station ' + data['SiteNo'][0])

In [ ]:
data.plot(x='DateTime', y='Discharge_cfs', title='Station ' + data['SiteNo'][0])

Below is an example where we save the figure to a `.png` file:

In [ ]:
data.plot(x='DateTime', y='Discharge_cfs', title='Station ' + data['SiteNo'][0])
plt.xlabel('Time')
plt.ylabel('Discharge (cfs)')

# to save your figure to a file, specify a name before the final plotting command
plt.savefig('USGStestplot.png')

plt.show()

## Using Logical Operators with DataFrames to Filter Values

Another useful data wrangling option is the ability to filter data from an existing pandas dataframe.

Filtering data is easily done using dataframe.column_name == "value". Your output will contain all rows that meet the criteria.

For example, you can filter using a comparison operator on numeric values. For example, you can select all rows from the dataframe that have discharge greater than 8500 cfs by filtering on the Discharge_in_cfs column.



In [ ]:
# create new dataframe from filter on values in the `Discharge_cfs` column greater than 8500 cfs
high_discharge_days = data[data.Discharge_cfs > 8500]

# print new dataframe
high_discharge_days